config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :dashboards do
  	resources :component_dashboards
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :manage, Dashboard, {user_id: user.id}
      can :manage, ComponentDashboard, {dashboard: {user_id: user.id}}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/component.rb
class Component < ApplicationRecord
	has_many :component_dashboards
	has_many :dashboards, through: :component_dashboards

	validates_uniqueness_of :data_type
	validates_presence_of :data_type
end

app/models/component_dashboard.rb
class ComponentDashboard < ApplicationRecord
	belongs_to :dashboard
	belongs_to :component
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
  has_many :component_dashboards
  has_many :components, through: :component_dashboards
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dashboards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/component_dashboards_controller.rb
class ComponentDashboardsController < ApplicationController
  before_action :set_component_dashboard, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @dashboard = Dashboard.find(params[:dashboard_id])
    @component_dashboards = @dashboard.component_dashboards
    respond_to do |format|
      format.html{}
      format.json{render json: @component_dashboards}
    end
  end

  def new
    @component_dashboard = ComponentDashboard.new
    @dashboard = Dashboard.find(params[:dashboard_id])
    @components_json = Component.all.to_json

  end

  def create
    @component_dashboard = ComponentDashboard.new(component_dashboard_params)
    @dashboard = Dashboard.find(params[:dashboard_id])
    respond_to do |format|
      if @component_dashboard.save
        @dashboard.component_dashboards << @component_dashboard
        format.html{redirect_to action: :index}
        format.json{render json: @component_dashboard, status: :ok}
      else
        format.html{redirect_to action: :new, notice: "ComponentDashboard could not be created."}
        format.json{render json: @component_dashboard.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
    @dashboard = Dashboard.find(params[:dashboard_id])
  end

  def update
    @component_dashboard = ComponentDashboard.find(params[:id])
    respond_to do |format|
      if @component_dashboard.update(component_dashboard_params.dup)
        format.json{render json: @component_dashboard, status: :ok}
      else
        format.json{render json: @component_dashboard.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @component_dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_component_dashboards_path, notice: 'ComponentDashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_component_dashboard
     @component_dashboard = ComponentDashboard.find(params[:id])
   end

  def component_dashboard_params
		params.require(:component_dashboard).permit(:component_id, :col, :row, :sizeX, :sizeY, :endpoint,
    :secret_key, :response_data_location, :refresh_time, :title, :subtitle
		)
	end


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  load_and_authorize_resource
  def show
    @dashboard = Dashboard.find(params[:id])

  end

  def index
    @dashboards = current_user.dashboards
    respond_to do |format|
      format.html{}
      format.json{render json: @dashboards, status: :ok }
    end
  end

  def new

  end

  def update
    @dashboard = Dashboard.find(params[:id])
    respond_to do |format|
      if @dashboard.update(dashboard_params.dup)
        format.json{render json: @dashboard, status: :ok}
      else
        format.json{render json: @dashboard.errors, status: :unprocessable_entity}
      end
    end
  end

  def create
    new_params = dashboard_params.dup
    @dashboard = Dashboard.new(new_params)
    respond_to do |format|
      if @dashboard.save
        format.html{redirect_to action: :index}
      else
        format.html{redirect_to action: :new, notice: "Dashboard could not be created."}
      end
    end
  end

  protected
  def dashboard_params
		params.require(:dashboard).permit(
      :name, :user_id, :dashboard_color
		)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/component_dashboards/edit.html.erb
<h1> Edit Component Dashboards</h1>

<%= form_for([@dashboard, @component_dashboard]) do |f| %>


<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div><div class="field">
  <%= f.label :subtitle %><br>
  <%= f.text_field :subtitle %>
</div>
<div class="field">
  <%= f.label :endpoint %><br>
  <%= f.text_field :endpoint %>
</div>
<div class="field">
 <%= f.label :response_data_location %><br>
 <%= f.text_field :response_data_location %>
</div>
<div class="field">
 <%= f.label :refresh_time %> <small>(In seconds)</small><br>
 <%= f.number_field :refresh_time %>
</div>
<div class="field">
 <%= f.label :secret_key %><br>
 <%= f.text_field :secret_key %>
</div>

<div class="field">
 <%= f.label :component_id %><br>
 <%= f.collection_select :component_id, Component.all ,:id,:name, {:include_blank => false} %>
</div>
 <%= f.hidden_field :dashboard_id %>

<div class="field">
 <%= f.label :col %><br>
 <%= f.number_field :col%>
</div>
<div class="field">
 <%= f.label :row %><br>
 <%= f.number_field :row %>
</div>


<div class="actions">
    <%= f.submit "Update", :class => "button-link"  %>
  </div>
<% end %>

app/views/component_dashboards/index.html.erb
<h1> Component Dashboards</h1>

<table>
  <thead>
    <tr>
      <th>Component id</th>
      <th>Dashboard id</th>
      <th>col</th>
      <th>row</th>
      <th>sizeX</th>
      <th>sizeY</th>
      <th>endpoint</th>
      <th>secret key</th>
    </tr>
  </thead>

  <tbody>
    <% @component_dashboards.each do |component_dashboard| %>
      <tr>
        <td><%= component_dashboard.component_id %></td>
        <td><%= component_dashboard.dashboard_id %></td>
        <td><%= component_dashboard.col %></td>
        <td><%= component_dashboard.row %></td>
        <td><%= component_dashboard.sizeX %></td>
        <td><%= component_dashboard.sizeY %></td>
        <td><%= component_dashboard.endpoint %></td>
        <td><%= component_dashboard.secret_key %></td>
        <td><%= button_to "Edit", edit_dashboard_component_dashboard_path(:id => component_dashboard.id), :method => :get %></td>
        <td><%= button_to "Delete", dashboard_component_dashboard_path(:id => component_dashboard.id), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/component_dashboards/new.html.haml
.div{'ng-controller'=>'newDashboardComponentsController', 'ng-init'=>"initComponents(#{@components_json})"}

  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="users"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "users")}'}
    Cantidad usuarios


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="messages"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "messages")}'}
    Cantidad mensajes enviados


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="diplomas"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "diplomas")}'}
    Cantidad diplomas enviados


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="absences"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "absences")}'}
    Cantidad asistencias


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="ranking"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "ranking")}'}
    Ranking de uso


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="deploy_battle"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "deploy_battle")}'}
    Deploy Battle


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="promotion"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "promotion")}'}
    Cambio de año


  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="surveys"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "surveys")}'}
    Encuestas

  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="altera_status"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "altera_status")}'}
    Altera Status

  %button.btn.btn-success{'ng-click'=>'currentSelectedDashboardComponent="custom"', 'ng-class'=>'{"selected":(currentSelectedDashboardComponent == "custom")}'}
    Custom dashboard component

  .div{'ng-if'=>'currentSelectedDashboardComponent=="custom"'}
    %h1 New Component Dashboards
    = form_for([@dashboard, @component_dashboard]) do |f|
      .field
        = f.label :title
        %br/
        = f.text_field :title
      .field
        = f.label :subtitle
        %br/
        = f.text_field :subtitle
      .field
        = f.label :endpoint
        %br/
        = f.text_field :endpoint
      .field
        = f.label :response_data_location
        %br/
        = f.text_field :response_data_location
      .field
        = f.label :refresh_time
        %small (In seconds)
        %br/
        = f.number_field :refresh_time
      .field
        = f.label :secret_key
        %br/
        = f.text_field :secret_key
      .field
        = f.label :component_id
        %br/
        = f.collection_select :component_id, Component.all ,:id,:name, {:include_blank => false}
      = f.hidden_field :dashboard_id
      .field
        = f.label :col
        %br/
        = f.number_field :col
      .field
        = f.label :row
        %br/
        = f.number_field :row

      .actions
        = f.submit "Create ComponentDashboard", :class => "button-link"

  .div{'ng-if'=>'currentSelectedDashboardComponent=="users" || currentSelectedDashboardComponent=="messages" || currentSelectedDashboardComponent=="diplomas" || currentSelectedDashboardComponent=="absences"|| currentSelectedDashboardComponent=="ranking" || currentSelectedDashboardComponent=="promotion" || currentSelectedDashboardComponent=="surveys" || currentSelectedDashboardComponent=="altera_status"' }
    %form{'ng-submit'=>"createPapinotasDashboard('#{dashboard_component_dashboards_path(format: :json)}', #{@dashboard.id}, papinotasApiKey, title, subtitle)"}
      %label Ingresa título
      %input{'ng-model'=>'title'}
      %label Ingresa subtitulo
      %input{'ng-model'=>'subtitle'}
      %label Ingresa tu Api Key de Papinotas
      %input{'ng-model'=>'papinotasApiKey'}
      %button{'type'=>'submit'} Crear componente

app/views/dashboards/index.html.haml
.row
  .col-sm-8.col-sm-offset-2
    %h1 My Dashboards
    .dashboard-links
      -@dashboards.each do |dashboard|
        =link_to dashboard_path(dashboard) do
          .dashboard-link
            =dashboard.name
    =link_to new_dashboard_path do
      .btn.btn-default
        Create Dashboard

app/views/dashboards/new.html.haml
.row
  .col-sm-8.col-sm-offset-2
    %h1 Creating Dashboard
    =form_for Dashboard.new do |f|
      =f.label :name
      =f.text_field :name, class: "form-control form-control--dash"
      =f.hidden_field :user_id, value: current_user.id
      %br

      %button.btn.btn-success{type: 'submit'}
        Create

app/views/dashboards/show.html.haml
=render partial:"menubar/usermenu"

.dashboard-container.clearfix#target{ 'ng-controller' => "DashboardsController", 'ng-cloak'=>'', "ng-style"=>"{'background-color':bgcolor}" , "ng-init"=>"dashboardId = #{@dashboard.id}",}
  %button.btn.fa.fa-paint-brush.text-primary{:colorpicker => "",  "colorpicker-position" => "bottom", "ng-model" => "bgcolor","ng-init" => "bgcolor='#{@dashboard.dashboard_color}'", :type => "text"}


  %h1.text-center
    =@dashboard.name

  %a.btn.btn-default.btn-byebyeFullScreen.text-right{:href => ""} adios fullscreen

  .gridster-container{'gridster'=>'gridsterOpts', 'ng-init'=>"fetchDashboardComponents('#{dashboard_component_dashboards_path(@dashboard, format: :json)}')"}
    %ul
      %li{'gridster-item'=>'dashboardComponent', 'ng-repeat'=>"dashboardComponent in dashboardComponents"}
        .gdstr-header.amount{'ng-if'=>'dashboardComponent.component.data_type == "amount"'}
          %h3.gdstr-title
            {{dashboardComponent.title}}
          %p.subtitle
            {{dashboardComponent.subtitle}}
          .loading-component{'ng-if'=>'dashboardComponent.loaded == false', 'ng-cloak'=>''}
            .fa.fa-spin.fa-circle-o-notch
          %h2.text-center{'ng-count-to'=>'{{dashboardComponent.amount}}', value: '{{dashboardComponent.amountOld}}', duration: '1', filter: "number"}

        .bar-chart{'ng-if'=>'dashboardComponent.component.data_type == "bar-chart"'}
          .loading-component{'ng-if'=>'dashboardComponent.loaded == false', 'ng-cloak'=>''}
            .fa.fa-spin.fa-circle-o-notch
          %canvas.chart.chart-bar{'chart-data'=>'dashboardComponent.data.values', 'chart-labels'=>'dashboardComponent.data.labels', 'chart-options' => 'dashboardComponent.chart_options'}
        .iframe{'ng-if'=>'dashboardComponent.component.data_type == "iframe"', style: 'height:100%;'}
          %iframe{ 'src'=>'{{dashboardComponent.endpoint | trustAsResourceUrl}}',  width: '100%', height: '100%'}
        .gdstr-header.amount{'ng-if'=>'dashboardComponent.component.data_type == "status-with-success-rate"'}
          .loading-component{'ng-if'=>'dashboardComponent.loaded == false', 'ng-cloak'=>''}
            .fa.fa-spin.fa-circle-o-notch
          %h3.gdstr-title
            {{dashboardComponent.title}}
          %p.subtitle
            Success rate: {{dashboardComponent.success_rate}}
          %p
            Status:
            %strong.text-success{'ng-if' => 'dashboardComponent.altera_status == true'}
              Ok
            %strong.text-danger{'ng-if' => 'dashboardComponent.altera_status == false'}
          .fa.fa-circle.fa-5x.text-success{'ng-if' => 'dashboardComponent.altera_status'}
          .fa.fa-circle.fa-5x.text-danger{'ng-if' => '!dashboardComponent.altera_status'}
        .gdstr-header.amount{'ng-if'=>'dashboardComponent.component.data_type =="ranking"'}
          %h3.gdstr-title
            {{dashboardComponent.title}}
          .loading-component{'ng-if'=>'dashboardComponent.loaded == false', 'ng-cloak'=>''}
            .fa.fa-spin.fa-circle-o-notch
          %ul
            %li{'ng-repeat' => "ranked_school in dashboardComponent.ranking track by $index"}
              {{$index + 1}}) School id {{ranked_school.school_id}}: {{ranked_school.school_messages}} messages

  = link_to "<button class='btn btn-default'>New Component Dashboard</button>".html_safe, new_dashboard_component_dashboard_path(dashboard_id: @dashboard.id)
  = link_to "<button class='btn btn-default'>List Component Dashboards</button>".html_safe, dashboard_component_dashboards_path(dashboard_id: @dashboard.id)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DashBattle
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body{"ng-app" => "DashBattle"}
    = render partial: 'layouts/navigation/navbar'
    = yield

    .footer
      %p
        ©#{Time.now.year}
        Tecnomei Labs, Santiago
        %i.fa.fa-hand-peace-o
        Chile

app/views/layouts/navigation/_navbar.html.haml
%nav.navbar.navbar--dashbattle
	.container-fluid
		.navbar-header
			%a.navbar-brand{:href => root_path}
				.navbar-logo
					%svg{:width => "100%", :height => "100%", :viewbox => "0 0 219 163", :xmlns => "http://www.w3.org/2000/svg"}
						%title Logo dashbattle
						%g{:fill => "none", "fill-rule" => "evenodd", :stroke => "#000000", "stroke-linecap" => "round"}
							%path{:class=>'logo-path1','stroke-miterlimit'=>'10' , 'stroke-dasharray'=>"300" , 'stroke-dashoffset'=>"300",  :d => "M16,141 L16,47.9793836 L104.015719,137.782015 C109.812379,143.69636 107.800995,148.490885 99.5090011,148.490885 L31,148.490885", "stroke-linejoin" => "round", "stroke-width" => "12"}
							%path{:class=>'logo-path2','stroke-miterlimit'=>'10' , 'stroke-dasharray'=>"500" , 'stroke-dashoffset'=>"500", :d => "M81,93 L81,83 C81,66 89,44 116,44 C143,44 147,73 147,73 C147,73 154,106 117,106 C80,106 96,86 117,86 C138,86 161,102 161,120 C161,136.098544 147,148 131.728169,148 L121.5,148", "stroke-width" => "12"}
							%path{:class=>'logo-path3',:stroke=>'yellow','stroke-miterlimit'=>'10' , 'stroke-dasharray'=>"300" , 'stroke-dashoffset'=>"300",:class=>'logo-path3', :d => "M139,33 C139,33 157.5,36 170.5,11 C167.5,25 159,55 204,37 C192,46 159,73 202,88 C186,90 175,100 180,110", "stroke-linejoin" => "round", "stroke-width" => "10"}
				.brand-name
					DashBattle

		.nav.navbar-nav.navbar-right
			- if user_signed_in?
				= link_to(dashboards_path) do
					%button.btn.btn-default.navbar-btn{:type => "button"}
						My Dashboards
				= link_to(destroy_user_session_path, :method => :delete) do
					%button.btn.btn-default.navbar-btn{:type => "button"}
						Logout
			- else
				= link_to(new_user_session_path)  do
					%button.btn.btn-default.navbar-btn{:type => "button"}
						Login
				= link_to(new_user_registration_path)  do
					%button.btn.btn-default.navbar-btn{:type => "button"}
						Register

app/views/menubar/_usermenu.html.haml
.menuBar.menuBar-user
  .menuBar-left
    %h2.menuBar-title Menu

  .menuBar-right
    %ul.list-inline
      %li.menuBar-item
        %a.btn.btn-default.js-triggerFullScreen{:href => "#"}
          %i.fa.fa-arrows-alt

      %li.menuBar-item
        Boton cambiar color
      %li.menuBar-item
        user name

app/views/pages/home.html.haml
.container
  %h1.text-center.u-mt100 Understand your data and own the world

.container-fluid.welcome-block{:style => "background-color: #fff"}
  %h1.title-home.text-center.u-mt100 Hola Bebe